### ISSUE TITLE
Config issue or bug ... using ArgoCD

### ISSUE THREAD

**Issue by cmoulliard** [redhat-developer/rhdh#1242]
## Issue

I created a proxy endpoint to access `argocd` when I launch backstage top of the main branch (commit: f996bf6) of this project: backstage-showcase but I cannot access `argocd` stuff

and see this message within the browser dev console:
```
XHR - http://localhost:7007/api/proxy/argocd/api/applications/quarkus-app-rhdh-1-bootstrap - 401 Unauthorized.
```

Do we have to configure something specifically ? 

Here is how I configured it
```
proxy:
  skipInvalidProxies: true
  endpoints:
    '/argocd/api':
      # url to the api of your hosted argoCD instance
      target: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/api/v1/
      changeOrigin: true
      # this line is required if your hosted argoCD instance has self-signed certificate
      secure: false
      headers:
        Cookie:
          $env: "argocd.token=<ARGOCD_AUTH_TOKEN>"

argocd:
  baseUrl: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/
  username: admin
  password: XXXXXXXXXXXXXX
  appLocatorMethods:
    - type: config
      instances:
        - name: argocdQShift
          url: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/ 
```

**Comment by karthikjeeyar** [comment]
@cmoulliard Can you try passing the `token` key/value in the instances array ?
```
argocd:
  baseUrl: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/
  username: admin
  password: XXXXXXXXXXXXXX
  appLocatorMethods:
    - type: config
      instances:
        - name: argocdQShift
          url: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/ 
          token: <your-token>
```
   Or the other option is pass the username password inside instances array like below
   
   ```
   argocd:
    appLocatorMethods:
      - type: 'config'
        instances:
          - name: main
            url: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/ 
            username: <username>
            password: <your-pwd>
```

**Comment by cmoulliard** [comment]
> Can you try passing the `token` key/value in the instances array ?

I don't configure anymore the proxy and use only username/password which is working fine
```
argocd:
 appLocatorMethods:
   - type: 'config'
     instances:
       - name: main
         url: https://openshift-gitops-server-openshift-gitops.apps.qshift.snowdrop.dev/ 
         username: <username>
         password: <your-pwd>
```
