### ISSUE TITLE
app.branding.iconLogo has no effect when running the downstream image

### ISSUE THREAD

**Issue by gashcrumb** [redhat-developer/rhdh#777]
### Describe the bug

When a user attempts to customize the favicon using ```app.branding.iconLogo``` the setting is ignored and only the Red Hat logo is shown for the tab icon.  However ```app.title``` does take effect.  This works as expected when running backstage-showcase locally in development mode.

### Expected Behavior

The user configured favorite icon is shown instead of the default Red Hat logo

### What are the steps to reproduce this bug?

1. Deploy RHDH using helm and set it up with a custom app config ConfigMap
2. Update the branding settings to:
```
data: 
  app-config-rhdh.yaml: |
    app: 
      branding: 
        iconLogo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAADAFBMVEVHcEyWcCiolEdoUSP+4DD7xRX8zBe4qVCtjDKtiCL+94mkgSWpiy6tmDmogyC1mzGvnkCjgCaypUW2pTvjuzbhuzfMvD2viBzWwjfYqBW2rU360R+3jRnz2jPg1ETmvzTPsCvZsDn8yhrvuR31ySL+7ETsxC68lCK2jyDhujrFmhq5sVPYrBzerS3zwh+9kBj3yBxWORf+5jL91CF/XB3swizdtTjrrRTitTD1yCO5sFfjujbnvS9KOi3DkBTovC/WqDKLcVr8yyP5yhzEiB+NYxj+81CMWx3q4VfjoxZ+Sg1XNRL7wRK2sF7itzGibhXFjRDQpDbl3VzcsDO/hBDyqQ7cnRXkqyLyuxr+6DuyeRPYoCXKgA/ZlRjbggq1r2XOoTBcOiBfPCMNBQTWz2TwrBnKmCXCvWr+60XFli5ySiTPiQouEQYlDgd8QAvl4XvHixe3s2y+kCn7zit+VhF1WheZgDnbuCGffSXYlBHDvnCsfRhzYRfGtURxWQrz1y6EYAjVwkbX03fw3kLRylf+93HEvWjp5X65smrAtGPt6XW7sGTx7oTd12H91hz91Bv8xRLjjAr96D791xz8yRf90B/91ib80R7+4y/91Rn90Bz9zyH+4jX9zRn92yT91iD6yBn8xxT8wxb+8EP6uw/0pQz+81r+82782TT+9Hz98VP++IXy30HnshTwuRX1uRL+5jb+7Tz+6Dj+6zj2uhD84DT760nrxij+4jPq4E798Ez+2i3+8k390hr5zyL1uxT5xhj+5zD6zh38xxvtvxv9zxr92S7+3Cr80SH+4C3wsA/3uRL92SP+4zb+6j7+81X3sQ/9yxm4aAj80hrqpg6+ZwnvoAztngv/9Ffehg3gigr1qhDxoA3eiQ3SewnplQv2wBrgnAz+7kT882T+5TvWlRDbkAr82zX38HX2viP93zjjmA7+82fJgAmwgyn+60+6egnyth359If94j/gvSP++ZCsdAiqjQ/++ZT40Cresxr99Wb++pr08ID//J/+/JaMm2H6AAAAlHRSTlMABgko/v7+AQJ0/iQVKFWdGChWnVse64L6/pT+rP7+m/Y1/vz+/t/TtSnrpP7H/tX+I/7+C+E6/qz+lninIO/RhXX+/jBa/jH+/uCR/mpoofln/h32/v2+/P7bTvLG/it6Durz9f6zvf4bGv77/v7+70Vx/vHmZ/5K/q/WtG39/v699P5X/i/+NGH+Wv7Y///////+AJaghAAAAYtJREFUOMtjYKAGcLTFL8+YlMyBVwFzbk4iXgVl7/Ky8CqoLS9hxyfP3vilFK8BLc31dcx45Dl6f6/6XoNHQVvX/9ZfDRW4FXT+/bf657dqRpwKunv+cK2o/FCEU0FH+4/Vnz++LcjEpYCp6SvX++LX2Wk4g7vq08o3r14+e5qAS0Fh/srlGc9TH4YF4lKR/mL5sicrHlzxdMBhS3zK42WPIuc4nzLXVcSuwjdo1Y3F585O37Je2cIMa7xZeZx3Wxw5Z9pC1gN69taaWOJDe+euPRs37dg9e9GUuYcs1eRFRNFVSMltU91sNIPlmNNhtv7JfdIqpjZ+wShKhMTWTNpwcMbJ49NmT521t3/mzMsLIsKjkb0lICwhu5Vl3rwz8+cbT50+l23CwglLQmNdkA3h5VfYvu/E9P6+vv6jFxfdvnn3ztLrMe4o9vBwquscMVigNIV1gs+SpRMnToy76o3uIUFODS3Jtev2n75w7f6te5e8DLElQm4+cRl9u4CQKH9XEzxplYmRgToAADVmlE2t74hfAAAAAElFTkSuQmCC
```
3. save the ConfigMap and delete the RHDH pod
4. The app should use the following favicon:

![image](https://github.com/janus-idp/backstage-showcase/assets/351660/eef25782-849f-45b7-99da-83eac32c7183)

### Versions of software used and environment
OCP 4.14.1
RHDH image version: 1.0-155

**Comment by gashcrumb** [comment]
Is this normally a build-time substitution that's done?

**Comment by invincibleJai** [comment]
Every browser pick favicon differently, 

we are having developer hub icon as favicon by default and dynamically updating it based on config i.e

```
app:
  title: Janus IDP Backstage jai
  baseUrl: http://localhost:3000
  branding:
    iconLogo: ${BASE64_EMBEDDED_ICON_LOGO}
```

**in chrome:**

<img width="645" alt="image" src="https://github.com/janus-idp/backstage-showcase/assets/5129024/d5d8cfad-9c23-4487-bc09-2f5c48ba911a">

it updated the favicon icon to RH icon and not what's provided in the config

**In firefox:**

<img width="875" alt="image" src="https://github.com/janus-idp/backstage-showcase/assets/5129024/116c8f6f-497a-454e-a0dc-4fa946eea2ef">

it shows default favicon icon i.e developer hub icon

**In Safari:**

<img width="717" alt="image" src="https://github.com/janus-idp/backstage-showcase/assets/5129024/a50a9ab3-4050-4341-ad37-9e4a2e827f06">


no favicon icon is shown
